package Basics;
import java.util.*;
class guessTheNum
{
    public static void main(String[] args)
    {
        Scanner sc=new Scanner(System.in);
        Random r = new Random();
        int random=r.nextInt(100)+1;
        System.out.print("Guess the number generated by computer (1-100) : ");
        int guess=sc.nextInt();
        int attempt=0;
        while(guess!=random)
        {
            if(guess<random)
            System.out.print("Try a higher number : ");
            else
            System.out.print("Try a lower number : ");
            guess=sc.nextInt();
            attempt++;
        }
        System.out.println("You guessed it right! (in "+attempt+" attempts)");
        sc.close();
    }
}